const ShopActionTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SECCESS: "FETCH_COLLECTION_SECCESS",
  FETCH_COLLECCTION_FAILURE: "FETCH_COLLECCTION_FAILURE",
};
export default ShopActionTypes;
